# Generated by Django 5.2.3 on 2026-06-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_colour_size_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                (
                    "colour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.colour",
                    ),
                ),
            ],
            options={
                "unique_together": {("colour", "language")},
            },
        ),
    ]
