# Generated by Django 4.2.16 on 2026-04-28 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("owner", "Owner"),
                            ("captain", "Captain"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=10,
                        verbose_name="account type",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Customers are verified immediately after email confirmation. Owners become verified after admin approves their documents.",
                        verbose_name="verified",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/profile_images/%Y/%m/",
                        verbose_name="profile image",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="address"),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="nationality",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Banned users cannot log in or access the platform.",
                        verbose_name="banned",
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the 60-day deactivation was requested. Account will be permanently purged after 60 days.",
                        null=True,
                        verbose_name="deactivated at",
                    ),
                ),
                (
                    "tokens_invalidated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Access tokens issued before this timestamp are rejected. Updated whenever the user triggers logout-from-all-devices.",
                        null=True,
                        verbose_name="tokens invalidated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=6, verbose_name="verification code"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="reset code")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True once the user has confirmed the code; allows the reset step.",
                        verbose_name="code verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "password reset code",
                "verbose_name_plural": "password reset codes",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fcm_token", models.TextField(unique=True, verbose_name="FCM token")),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=10,
                        null=True,
                        verbose_name="device type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user device",
                "verbose_name_plural": "user devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        default="individual",
                        max_length=10,
                        verbose_name="owner type",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="address"),
                ),
                (
                    "national_id_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="national ID number",
                    ),
                ),
                (
                    "national_id_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="owners/national_ids/%Y/%m/",
                        verbose_name="national ID image",
                    ),
                ),
                (
                    "tax_card",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="owners/tax_cards/%Y/%m/",
                        verbose_name="tax card document",
                    ),
                ),
                (
                    "commercial_registration",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="owners/commercial_registrations/%Y/%m/",
                        verbose_name="commercial registration document",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="verification status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="rejection reason"
                    ),
                ),
                (
                    "validation_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validation expires at"
                    ),
                ),
                (
                    "can_renew_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="can renew at"
                    ),
                ),
                (
                    "rejection_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="rejection count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "owner profile",
                "verbose_name_plural": "owner profiles",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="referral code",
                    ),
                ),
                (
                    "saved_items_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="saved items count"
                    ),
                ),
                (
                    "quiz_preferences",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Stores onboarding quiz answers as JSON.",
                        null=True,
                        verbose_name="quiz preferences",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer profile",
                "verbose_name_plural": "customer profiles",
            },
        ),
    ]
