# Generated by Django 4.2.16 on 2026-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("admin", "Admin")],
                db_index=True,
                default="customer",
                max_length=10,
                verbose_name="account type",
            ),
        ),
        migrations.DeleteModel(
            name="OwnerProfile",
        ),
    ]
