# Generated by Django 4.2.16 on 2026-05-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "user_type",
                    models.CharField(
                        choices=[("customer", "Customer"), ("owner", "Owner")],
                        default="customer",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("nl", "Dutch"),
                            ("ru", "Russian"),
                            ("pt", "Portuguese"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("hi", "Hindi"),
                            ("ko", "Korean"),
                            ("es", "Spanish"),
                        ],
                        max_length=10,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="FAQ.faq",
                    ),
                ),
            ],
            options={
                "unique_together": {("faq", "language")},
            },
        ),
    ]
