# Generated by Django 5.2.3 on 2026-06-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FAQ", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="user_type",
        ),
    ]
