# Generated by Django 4.2.16 on 2026-05-02 15:38

import apps.core.utils.upload_utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=70, verbose_name="full name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("trip", "Trip"),
                            ("rent", "Rent"),
                            ("support", "Support"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        verbose_name="subject",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(
                            apps.core.utils.upload_utils.upload_to_uuid,
                            *(),
                            **{"folder_name": "contact_messages"}
                        ),
                        verbose_name="image",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, verbose_name="url")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="contact_us.contactcontent",
                        verbose_name="contact content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                ("value", models.CharField(max_length=255, verbose_name="value")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_infos",
                        to="contact_us.contactcontent",
                        verbose_name="contact content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "icon",
                    models.ImageField(
                        upload_to=functools.partial(
                            apps.core.utils.upload_utils.upload_to_uuid,
                            *(),
                            **{"folder_name": "contact_icons"}
                        ),
                        verbose_name="icon",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icons",
                        to="contact_us.contactinfo",
                        verbose_name="contact info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactContentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(max_length=10, verbose_name="language code"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="contact_us.contactcontent",
                        verbose_name="contact content",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contactinfo",
            constraint=models.UniqueConstraint(
                fields=("type",), name="unique_contact_info_type_per_contact"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactcontenttranslation",
            unique_together={("contact_content", "language_code")},
        ),
    ]
