# Generated by Django 5.2.3 on 2026-06-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="contactcontenttranslation",
            name="contact_content",
        ),
        migrations.AlterUniqueTogether(
            name="contactcontenttranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="contacticon",
            name="contact_info",
        ),
        migrations.DeleteModel(
            name="SocialMediaLink",
        ),
        migrations.DeleteModel(
            name="ContactContent",
        ),
        migrations.DeleteModel(
            name="ContactContentTranslation",
        ),
        migrations.DeleteModel(
            name="ContactIcon",
        ),
        migrations.DeleteModel(
            name="ContactInfo",
        ),
    ]
