# Generated by Django 5.2.3 on 2025-07-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='state',
        ),
    ]
