# Generated by Django 5.2.3 on 2025-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prouducts', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
