# Generated by Django 5.2.3 on 2025-07-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_country_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
